### PR TITLE
Picture-in-Picture Fix

### LINKED ISSUE #122: Pip should be optional and return current state
The way it's today pip is forcefully enabled and can't be disabled, nor are we able to fetch current status (is in pip mode or not), that's crucial because some applications use other solutions to continue playback in background.

### PR DESCRIPTION
**Pull request by arthurgeron**
- Picture-in-picture now optional and disabled by default, fixes #122 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 export * from './enums';
 export * from './types';
-import IVSPlayer from './IVSPlayer';
+export { default as IVSPlayer } from './IVSPlayer';
+export type { IVSPlayerProps } from './IVSPlayer';
```
Comment (dawhitla) [inline src/index.ts:4]: Since the component we export is the `IVSPlayerContainer`
```
const IVSPlayerContainer = React.forwardRef<IVSPlayerRef, Props>
```
The correct type to export here is `type Props = {` 

However can we split changes to how we export types / components to a separate PR?

File: src/IVSPlayer.tsx [hunk 2]
```diff
@@ -37,6 +37,7 @@ type IVSPlayerProps = {
   resizeMode?: ResizeMode;
   logLevel?: LogLevel;
   progressInterval?: number;
+  pipEnabled?: boolean;
```
Comment (dawhitla) [inline src/IVSPlayer.tsx:40]: `pipEnabled` should also be added to the **Props** as well.

```
type Props = {
  style?: ViewStyle;
  testID?: string;
  paused?: boolean;
  muted?: boolean;
```

File: android/src/main/java/com/amazonaws/ivs/reactnative/player/AmazonIvsView.kt [hunk 3]
```diff
@@ -337,8 +343,10 @@ class AmazonIvsView(private val context: ThemedReactContext) : FrameLayout(conte
         data.putMap("playerData", playerData)
 
         reactContext.getJSModule(RCTEventEmitter::class.java).receiveEvent(id, Events.DATA.toString(), data)
-      }
-      else -> {}
```
Comment (dawhitla) [inline android/src/main/java/com/amazonaws/ivs/reactnative/player/AmazonIvsView.kt:341]: We should keep this `else -> {}` as removing it caused this issue https://github.com/aws/amazon-ivs-react-native-player/pull/113

File: android/src/main/AndroidManifest.xml [hunk 4]
```diff
@@ -1,5 +1,4 @@
-<manifest xmlns:android="http://schemas.android.com/apk/res/android"
-          package="com.amazonaws.ivs.reactnative.player">
+<manifest xmlns:android="http://schemas.android.com/apk/res/android"  >
```
Comment (dawhitla) [inline android/src/main/AndroidManifest.xml:1]: What does dropping the `package="com.amazonaws.ivs.reactnative.player"` prop here do?
Is it related to moving the namespace info android/build.gradle ?

**Review by dawhitla — CHANGES_REQUESTED** [review]
Just a couple of asks here on the PR. Additionally we are currently working on a PR to address some of the functional differences between PiP usage on Android vs iOS.

File: android/src/main/AndroidManifest.xml (hunk 4 above)
Comment (arthurgeron) [reply android/src/main/AndroidManifest.xml:1]: It's part of the [changes](https://github.com/react-native-community/discussions-and-proposals/issues/671) necessary to make this lib compatible with RN 0.73

File: src/IVSPlayer.tsx [hunk 5]
```diff
@@ -25,7 +25,7 @@ import type {
   ResizeMode,
 } from './types';
 
-type IVSPlayerProps = {
+export type IVSPlayerProps = {
```
[the remark this answers is not in the document]
Comment (arthurgeron) [reply src/IVSPlayer.tsx:28]: It's common for libs to export the Props types for their main components, it's useful when components have to be extended, wrapped, etc. If there are no downsides maybe we can let this remain exported?

**Comment by arthurgeron** [comment]
> Just a couple of asks here on the PR. Additionally we are currently working on a PR to address some of the functional differences between PiP usage on Android vs iOS.

Sounds great, I hope my changes are compatible, having some control over pip is a huge deal at my company since it'd create strange behaviors, for example: We use "track player" like lib to control and execute background playback; without any control, the pip would automatically start and duplicate the playback audio.

File: android/src/main/java/com/amazonaws/ivs/reactnative/player/AmazonIvsView.kt (hunk 3 above)
Comment (arthurgeron) [reply android/src/main/java/com/amazonaws/ivs/reactnative/player/AmazonIvsView.kt:341]: Yes that warning was actually the reason behind that specific change,  of adding a `else` statement I added the other possible states of the player inside the loop following android studio's/Kotlin's own suggestions, if you prefer I can revert this change.

File: src/index.ts (hunk 1 above)
Comment (arthurgeron) [reply src/index.ts]: Thank you for the feedback, I've moved these changes over to [this](https://github.com/aws/amazon-ivs-react-native-player/pull/152) PR

File: android/src/main/AndroidManifest.xml (hunk 4 above)
Comment (arthurgeron) [reply android/src/main/AndroidManifest.xml:1]: I believe other changes, such as the Gradle plugin can be made after RN 0.73 is released, but this small change will at least bring minimum compatibility.

File: android/build.gradle [hunk 6]
```diff
@@ -35,10 +35,11 @@ def pkgData = new JsonSlurper().parseText(rootPkg.text)
 def sdk_version = pkgData.version
 
 android {
+  namespace = "com.amazonaws.ivs.reactnative.player"
   compileSdkVersion getExtOrIntegerDefault('compileSdkVersion')
   buildToolsVersion getExtOrDefault('buildToolsVersion')
   defaultConfig {
-    minSdkVersion 21
+    minSdkVersion 26
```
Comment (dawhitla) [inline android/build.gradle:42]: Looks like we're getting a build issue here:
https://github.com/aws/amazon-ivs-react-native-player/actions/runs/5904085265/job/16025249877?pr=151#step:11:817

File: example/android/build.gradle [hunk 7]
```diff
@@ -3,9 +3,9 @@
 buildscript {
     ext {
         buildToolsVersion = "31.0.0"
-        minSdkVersion = 21
-        compileSdkVersion = 31
-        targetSdkVersion = 31
+        minSdkVersion = rootProject.ext.minSdkVersion
+        compileSdkVersion = rootProject.ext.targetSdkVersion
+        targetSdkVersion = rootProject.ext.targetSdkVersion
```
Comment (dawhitla) [inline example/android/build.gradle:8]: 👍

Comment (arthurgeron) [reply example/android/build.gradle]: Unfortunately it seems example android project can't access rootProject's data.

**Comment by arthurgeron-work** [comment]
@dawhitia Not sure why the android e2e tests are failing

File: android/src/main/AndroidManifest.xml (hunk 4 above)
Comment (dawhitla) [reply android/src/main/AndroidManifest.xml:1]: awesome, thank you 👍

File: android/src/main/java/com/amazonaws/ivs/reactnative/player/AmazonIvsView.kt (hunk 3 above)
Comment (dawhitla) [reply android/src/main/java/com/amazonaws/ivs/reactnative/player/AmazonIvsView.kt:341]: Ahh, great! just drop a comment here so future us does not yank these alternate cases and cause a regression 👍

**Comment by dawhitla** [comment]
> > 
> 
> I cleared the build cache and re-running 👍

```
Native stacktrace dump:
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
```

currently tracking down the root cause here when trying to run the build on emulator.

File: android/src/main/java/com/amazonaws/ivs/reactnative/player/AmazonIvsView.kt (hunk 3 above)
Comment (arthurgeron-work) [reply android/src/main/java/com/amazonaws/ivs/reactnative/player/AmazonIvsView.kt:341]: done!

**Comment by arthurgeron-work** [comment]
> > > 
> > 
> > 
> > I cleared the build cache and re-running 👍
> 
> ```
> Native stacktrace dump:
> java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
> ```
> 
> currently tracking down the root cause here when trying to run the build on emulator.

It looks like Soloader is missing, I've noticed it isn't specified in build.gradle's `dependencies` field, could that be it?

I'm not sure if there are other required steps to run detox tests aside from a specific AVD name, but I wasn't able to run it locally, unfortunately.

**Comment by dawhitla** [comment]
> 



> > > > 
> > > 
> > > 
> > > I cleared the build cache and re-running 👍
> > 
> > 
> > ```
> > Native stacktrace dump:
> > java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > currently tracking down the root cause here when trying to run the build on emulator.
> 
> It looks like Soloader is missing, I've noticed it isn't specified in build.gradle's `dependencies` field, could that be it?
> 
> I'm not sure if there are other required steps to run detox tests aside from a specific AVD name, but I wasn't able to run it locally, unfortunately.

Considering we haven't been able to determine the root cause here, can we split the RN 0.73 compatibility into its own PR ?
I'd like to get all the PiP related work in and stable to reduce the amount of in-flight changes we have right now.

**Comment by dawhitla** [comment]
> I'm not sure if there are other required steps to run detox tests aside from a specific AVD name, but I wasn't able to run it locally, unfortunately.

Can you let me know what is blocking you? Currently it expects the emulator to already be running before running 

for build
`e2e:build:android:release`
start emulator, then run
`e2e:test:android:release`

**Comment by arthurgeron** [comment]
> > 
> 
> > > > > 
> > > > 
> > > > 
> > > > I cleared the build cache and re-running 👍
> > > 
> > > 
> > > ```
> > > Native stacktrace dump:
> > > java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > currently tracking down the root cause here when trying to run the build on emulator.
> > 
> > 
> > It looks like Soloader is missing, I've noticed it isn't specified in build.gradle's `dependencies` field, could that be it?
> > I'm not sure if there are other required steps to run detox tests aside from a specific AVD name, but I wasn't able to run it locally, unfortunately.
> 
> Considering we haven't been able to determine the root cause here, can we split the RN 0.73 compatibility into its own PR ? I'd like to get all the PiP related work in and stable to reduce the amount of in-flight changes we have right now.

Agreed! FYI I've merged the changes and fixes related to PIP into a single commit.  I'll be opening another PR for the RN 0.73 upgrade

**Comment by arthurgeron-work** [comment]
it should build properly after my last commit

**Comment by arthurgeron** [comment]
@dawhitla  I've fixed the android build errors, all checks are now green.

**Review by dawhitla — APPROVED** [review]
Thank you for the patience on this 👍
